-- Insert booking translations
INSERT INTO translations (key, locale, content, namespace) VALUES
  -- English translations
  ('bookings.title', 'en', 'My Bookings', 'bookings'),
  ('bookings.empty.title', 'en', 'No Bookings Found', 'bookings'),
  ('bookings.empty.description', 'en', 'You haven''t made any bookings yet.', 'bookings'),
  ('bookings.empty.cta', 'en', 'Browse Events', 'bookings'),
  ('bookings.ticket_count', 'en', '{count} ticket | {count} tickets', 'bookings'),
  ('bookings.download', 'en', 'Download', 'bookings'),
  ('bookings.view_details', 'en', 'View Details', 'bookings'),
  ('bookings.hide_details', 'en', 'Hide Details', 'bookings'),
  ('bookings.status.valid', 'en', 'Valid', 'bookings'),
  ('bookings.status.used', 'en', 'Used', 'bookings'),
  ('bookings.status.cancelled', 'en', 'Cancelled', 'bookings'),
  ('bookings.ticket_used', 'en', 'Ticket Used', 'bookings'),
  ('bookings.ticket_not_used', 'en', 'Ticket Not Used', 'bookings'),
  ('bookings.scanned_at', 'en', 'Scanned at {location}', 'bookings'),
  ('bookings.scanned_by', 'en', 'by {name}', 'bookings'),
  ('bookings.transfer_ticket', 'en', 'Transfer Ticket', 'bookings'),
  ('bookings.important_info', 'en', 'Important Information', 'bookings'),
  ('bookings.info.arrival', 'en', 'Please arrive at least 30 minutes before the event starts', 'bookings'),
  ('bookings.info.qr_code', 'en', 'Have your ticket QR code ready for scanning at the entrance', 'bookings'),
  ('bookings.info.dress_code', 'en', 'Follow the event''s dress code and guidelines', 'bookings'),
  ('bookings.info.support', 'en', 'For any queries, contact our support team', 'bookings'),
  ('bookings.view_all', 'en', 'View all your bookings →', 'bookings'),

  -- French translations
  ('bookings.title', 'fr', 'Mes Réservations', 'bookings'),
  ('bookings.empty.title', 'fr', 'Aucune Réservation Trouvée', 'bookings'),
  ('bookings.empty.description', 'fr', 'Vous n''avez pas encore fait de réservation.', 'bookings'),
  ('bookings.empty.cta', 'fr', 'Parcourir les Événements', 'bookings'),
  ('bookings.ticket_count', 'fr', '{count} billet | {count} billets', 'bookings'),
  ('bookings.download', 'fr', 'Télécharger', 'bookings'),
  ('bookings.view_details', 'fr', 'Voir les Détails', 'bookings'),
  ('bookings.hide_details', 'fr', 'Masquer les Détails', 'bookings'),
  ('bookings.status.valid', 'fr', 'Valide', 'bookings'),
  ('bookings.status.used', 'fr', 'Utilisé', 'bookings'),
  ('bookings.status.cancelled', 'fr', 'Annulé', 'bookings'),
  ('bookings.ticket_used', 'fr', 'Billet Utilisé', 'bookings'),
  ('bookings.ticket_not_used', 'fr', 'Billet Non Utilisé', 'bookings'),
  ('bookings.scanned_at', 'fr', 'Scanné à {location}', 'bookings'),
  ('bookings.scanned_by', 'fr', 'par {name}', 'bookings'),
  ('bookings.transfer_ticket', 'fr', 'Transférer le Billet', 'bookings'),
  ('bookings.important_info', 'fr', 'Informations Importantes', 'bookings'),
  ('bookings.info.arrival', 'fr', 'Veuillez arriver au moins 30 minutes avant le début de l''événement', 'bookings'),
  ('bookings.info.qr_code', 'fr', 'Ayez votre code QR prêt pour le scan à l''entrée', 'bookings'),
  ('bookings.info.dress_code', 'fr', 'Respectez le code vestimentaire et les directives de l''événement', 'bookings'),
  ('bookings.info.support', 'fr', 'Pour toute question, contactez notre équipe de support', 'bookings'),
  ('bookings.view_all', 'fr', 'Voir toutes vos réservations →', 'bookings')
ON CONFLICT (key, locale) DO UPDATE
SET content = EXCLUDED.content;